/**
 * [중국어 별자리 퍼즐 - 데이터베이스]
 */

const TILE_DATA = {
  // 인물 & 대명사 (누락되었던 她 추가!)
  wo: { hanzi: '我', pinyin: 'wǒ' },
  ta: { hanzi: '他', pinyin: 'tā' },
  ta_f: { hanzi: '她', pinyin: 'tā' },
  ni: { hanzi: '你', pinyin: 'nǐ' },
  mama: { hanzi: '妈妈', pinyin: 'māma' },
  baba: { hanzi: '爸爸', pinyin: 'bàba' },
  yeye: { hanzi: '爷爷', pinyin: 'yéye' },
  nainai: { hanzi: '奶奶', pinyin: 'nǎinai' },
  laoshi: { hanzi: '老师', pinyin: 'lǎoshī' },
  pengyou: { hanzi: '朋友', pinyin: 'péngyou' },
  gege: { hanzi: '哥哥', pinyin: 'gēge' },
  jiejie: { hanzi: '姐姐', pinyin: 'jiějie' },
  didi: { hanzi: '弟弟', pinyin: 'dìdi' },
  meimei: { hanzi: '妹妹', pinyin: 'mèimei' },
  yisheng: { hanzi: '医生', pinyin: 'yīshēng' },
  xuesheng: { hanzi: '学生', pinyin: 'xuésheng' },
  shei: { hanzi: '谁', pinyin: 'shéi' },

  // 동사
  he_v1: { hanzi: '喝', pinyin: 'hē' },
  he_v2: { hanzi: '喝', pinyin: 'hē' },
  chi1: { hanzi: '吃', pinyin: 'chī' },
  chi2: { hanzi: '吃', pinyin: 'chī' },
  qu1: { hanzi: '去', pinyin: 'qù' },
  qu2: { hanzi: '去', pinyin: 'qù' },
  kan1: { hanzi: '看', pinyin: 'kàn' },
  kan2: { hanzi: '看', pinyin: 'kàn' },
  mai1: { hanzi: '买', pinyin: 'mǎi' },
  mai2: { hanzi: '买', pinyin: 'mǎi' },
  xihuan1: { hanzi: '喜欢', pinyin: 'xǐhuān' },
  xihuan2: { hanzi: '喜欢', pinyin: 'xǐhuān' },
  ai: { hanzi: '爱', pinyin: 'ài' },
  shuo: { hanzi: '说', pinyin: 'shuō' },
  ting: { hanzi: '听', pinyin: 'tīng' },
  xuexi: { hanzi: '学习', pinyin: 'xuéxí' },
  hui: { hanzi: '会', pinyin: 'huì' },
  dasuan: { hanzi: '打算', pinyin: 'dǎsuàn' },
  kai: { hanzi: '开', pinyin: 'kāi' },
  wang: { hanzi: '忘', pinyin: 'wàng' },
  wangji: { hanzi: '忘记', pinyin: 'wàngjì' },
  xiao: { hanzi: '笑', pinyin: 'xiào' },
  neng: { hanzi: '能', pinyin: 'néng' },
  tingdong: { hanzi: '听懂', pinyin: 'tīngdǒng' },

  // 명사 (사물, 장소, 시간 등)
  shui: { hanzi: '水', pinyin: 'shuǐ' },
  kafei: { hanzi: '咖啡', pinyin: 'kāfēi' },
  fan: { hanzi: '饭', pinyin: 'fàn' },
  pingguo: { hanzi: '苹果', pinyin: 'píngguǒ' },
  beijing: { hanzi: '北京', pinyin: 'běijīng' },
  jia: { hanzi: '家', pinyin: 'jiā' },
  shu: { hanzi: '书', pinyin: 'shū' },
  dianshi: { hanzi: '电视', pinyin: 'diànshì' },
  mianbao: { hanzi: '面包', pinyin: 'miànbāo' },
  mian: { hanzi: '面', pinyin: 'miàn' },
  cha: { hanzi: '茶', pinyin: 'chá' },
  xuexiao: { hanzi: '学校', pinyin: 'xuéxiào' },
  shangdian: { hanzi: '商店', pinyin: 'shāngdiàn' },
  yiyuan: { hanzi: '医院', pinyin: 'yīyuàn' },
  dianying: { hanzi: '电影', pinyin: 'diànyǐng' },
  pijiu: { hanzi: '啤酒', pinyin: 'píjiǔ' },
  hanyu_zh: { hanzi: '汉语', pinyin: 'hànyǔ' },
  hanyu_kr: { hanzi: '韩语', pinyin: 'hányǔ' },
  ge: { hanzi: '歌', pinyin: 'gē' },
  zhongguo: { hanzi: '中国', pinyin: 'zhōngguó' },
  mingtian: { hanzi: '明天', pinyin: 'míngtiān' },
  pashan: { hanzi: '爬山', pinyin: 'pá shān' },
  xiayu: { hanzi: '下雨', pinyin: 'xià yǔ' },
  xinche: { hanzi: '新车', pinyin: 'xīn chē' },
  che: { hanzi: '车', pinyin: 'chē' },
  shengri: { hanzi: '生日', pinyin: 'shēngrì' },

  // 부사, 접속사, 조사 (누락되었던 没有, 啊 추가!)
  bu: { hanzi: '不', pinyin: 'bù' },
  hen: { hanzi: '很', pinyin: 'hěn' },
  dou: { hanzi: '都', pinyin: 'dōu' },
  ye: { hanzi: '也', pinyin: 'yě' },
  jintian: { hanzi: '今天', pinyin: 'jīntiān' },
  gangcai: { hanzi: '刚才', pinyin: 'gāngcái' },
  yinwei: { hanzi: '因为', pinyin: 'yīnwèi' },
  suoyi: { hanzi: '所以', pinyin: 'suǒyǐ' },
  zai: { hanzi: '在', pinyin: 'zài' },
  men: { hanzi: '们', pinyin: 'men' },
  de1: { hanzi: '的', pinyin: 'de' },
  de2: { hanzi: '的', pinyin: 'de' },
  le: { hanzi: '了', pinyin: 'le' },
  ma: { hanzi: '吗', pinyin: 'ma' },
  ba: { hanzi: '吧', pinyin: 'ba' },
  hao: { hanzi: '好', pinyin: 'hǎo' },
  gaoxing: { hanzi: '高兴', pinyin: 'gāoxìng' },
  mang: { hanzi: '忙', pinyin: 'máng' },
  lian: { hanzi: '连', pinyin: 'lián' },
  meiyou: { hanzi: '没有', pinyin: 'méiyǒu' },
  a_part: { hanzi: '啊', pinyin: 'a' },
  he_conj1: { hanzi: '和', pinyin: 'hé' },
  he_conj2: { hanzi: '和', pinyin: 'hé' },
  he_conj3: { hanzi: '和', pinyin: 'hé' },
};

const STAGES = [
  {
    level: 1,
    title: '대화 1: Y자 합류 (会)',
    nodes: [
      { id: 'n1', x: 20, y: 30, expect: 'shei', customHint: 'A 시작' },
      { id: 'n2', x: 20, y: 70, expect: 'wo', customHint: 'B 시작' },
      { id: 'n3', x: 45, y: 50, expect: 'hui' },
      { id: 'n4', x: 70, y: 50, expect: 'shuo' },
      { id: 'n5', x: 90, y: 50, expect: 'hanyu_zh' },
    ],
    paths: [
      { from: 'n1', to: 'n3', type: 'a' },
      { from: 'n2', to: 'n3', type: 'b' },
      { from: 'n3', to: 'n4', type: 'common' },
      { from: 'n4', to: 'n5', type: 'common' },
    ],
    pool: ['shei', 'wo', 'hui', 'shuo', 'hanyu_zh'],
    answer:
      "A: 谁会说汉语？<br>B: 我会说汉语。<br><span class='kor'>A: 누가 중국어 말할 줄 아나요?<br>B: 저는 중국어를 말할 줄 알아요.</span>",
  },

  {
    level: 2,
    title: '대화 2: 교차점 분기 (打算/会)',
    nodes: [
      { id: 'n1', x: 10, y: 35, expect: 'wo', customHint: 'A 시작' },
      { id: 'n2', x: 30, y: 35, expect: 'dasuan' },
      { id: 'n3', x: 50, y: 50, expect: 'mingtian', customHint: 'B 시작' },
      { id: 'n4', x: 70, y: 25, expect: 'qu1' },
      { id: 'n5', x: 90, y: 15, expect: 'pashan' },
      { id: 'n6', x: 70, y: 75, expect: 'hui' },
      { id: 'n7', x: 90, y: 85, expect: 'xiayu' },
    ],
    paths: [
      { from: 'n1', to: 'n2', type: 'a' },
      { from: 'n2', to: 'n3', type: 'a' },
      { from: 'n3', to: 'n4', type: 'a' },
      { from: 'n4', to: 'n5', type: 'a' },
      { from: 'n3', to: 'n6', type: 'b' },
      { from: 'n6', to: 'n7', type: 'b' },
    ],
    pool: ['wo', 'dasuan', 'mingtian', 'qu1', 'pashan', 'hui', 'xiayu'],
    answer:
      "A: 我打算明天去爬山。<br>B: 明天会下雨。<br><span class='kor'>A: 저는 내일 등산 갈 계획이에요.<br>B: 내일 비가 올 거예요.</span>",
  },

  {
    level: 3,
    title: '대화 3: 상하 분리 대화 (没有啊)',
    nodes: [
      { id: 'n1', x: 15, y: 25, expect: 'ta_f', customHint: 'A 시작' },
      { id: 'n2', x: 35, y: 25, expect: 'mai1' },
      { id: 'n3', x: 55, y: 25, expect: 'le' },
      { id: 'n4', x: 75, y: 25, expect: 'xinche' },
      { id: 'n5', x: 90, y: 25, expect: 'ma' },

      { id: 'n6', x: 10, y: 55, expect: 'meiyou', customHint: 'B 시작' },
      { id: 'n7', x: 25, y: 55, expect: 'a_part' },
      { id: 'n8', x: 40, y: 55, expect: 'ta_f' },
      { id: 'n9', x: 55, y: 55, expect: 'lian' },
      { id: 'n10', x: 70, y: 55, expect: 'che' },
      { id: 'n11', x: 85, y: 55, expect: 'dou' },
      { id: 'n12', x: 75, y: 80, expect: 'bu' },
      { id: 'n13', x: 60, y: 80, expect: 'hui' },
      { id: 'n14', x: 45, y: 80, expect: 'kai' },
    ],
    paths: [
      { from: 'n1', to: 'n2', type: 'a' },
      { from: 'n2', to: 'n3', type: 'a' },
      { from: 'n3', to: 'n4', type: 'a' },
      { from: 'n4', to: 'n5', type: 'a' },
      { from: 'n6', to: 'n7', type: 'b' },
      { from: 'n7', to: 'n8', type: 'b' },
      { from: 'n8', to: 'n9', type: 'b' },
      { from: 'n9', to: 'n10', type: 'b' },
      { from: 'n10', to: 'n11', type: 'b' },
      { from: 'n11', to: 'n12', type: 'b' },
      { from: 'n12', to: 'n13', type: 'b' },
      { from: 'n13', to: 'n14', type: 'b' },
    ],
    pool: [
      'ta_f',
      'mai1',
      'le',
      'xinche',
      'ma',
      'meiyou',
      'a_part',
      'ta_f',
      'lian',
      'che',
      'dou',
      'bu',
      'hui',
      'kai',
    ],
    answer:
      "A: 她买了新车吗?<br>B: 没有啊，她连车都不会开。<br><span class='kor'>A: 그녀는 새 차를 샀나요?<br>B: 아니요, 그녀는 운전도 못 해요.</span>",
  },

  {
    level: 4,
    title: '대화 4: 공통 주어 시작 (他)',
    nodes: [
      { id: 'n1', x: 10, y: 50, expect: 'ta', customHint: 'A/B 공통' },
      { id: 'n2', x: 25, y: 20, expect: 'wang' },
      { id: 'n3', x: 40, y: 20, expect: 'le' },
      { id: 'n4', x: 55, y: 20, expect: 'wo' },
      { id: 'n5', x: 70, y: 20, expect: 'de1' },
      { id: 'n6', x: 85, y: 20, expect: 'shengri' },
      { id: 'n7', x: 95, y: 40, expect: 'ba' },
      { id: 'n8', x: 30, y: 80, expect: 'bu' },
      { id: 'n9', x: 50, y: 80, expect: 'hui' },
      { id: 'n10', x: 70, y: 80, expect: 'wangji' },
      { id: 'n11', x: 90, y: 80, expect: 'de2' },
    ],
    paths: [
      { from: 'n1', to: 'n2', type: 'a' },
      { from: 'n2', to: 'n3', type: 'a' },
      { from: 'n3', to: 'n4', type: 'a' },
      { from: 'n4', to: 'n5', type: 'a' },
      { from: 'n5', to: 'n6', type: 'a' },
      { from: 'n6', to: 'n7', type: 'a' },
      { from: 'n1', to: 'n8', type: 'b' },
      { from: 'n8', to: 'n9', type: 'b' },
      { from: 'n9', to: 'n10', type: 'b' },
      { from: 'n10', to: 'n11', type: 'b' },
    ],
    pool: [
      'ta',
      'wang',
      'le',
      'wo',
      'de1',
      'shengri',
      'ba',
      'bu',
      'hui',
      'wangji',
      'de2',
    ],
    answer:
      "A: 他忘了我的生日吧？<br>B: 他不会忘记的。<br><span class='kor'>A: 그는 제 생일을 잊어버린 거죠?<br>B: 그는 잊지 않았을 거예요.</span>",
  },

  {
    level: 5,
    title: '대화 5: 짧은 분기 (能)',
    nodes: [
      { id: 'n1', x: 15, y: 50, expect: 'ta_f', customHint: 'A/B 공통' },
      { id: 'n2', x: 40, y: 25, expect: 'gangcai' },
      { id: 'n3', x: 65, y: 25, expect: 'xiao' },
      { id: 'n4', x: 90, y: 25, expect: 'le' },
      { id: 'n5', x: 40, y: 75, expect: 'neng' },
      { id: 'n6', x: 65, y: 75, expect: 'tingdong' },
      { id: 'n7', x: 90, y: 75, expect: 'hanyu_kr' },
    ],
    paths: [
      { from: 'n1', to: 'n2', type: 'a' },
      { from: 'n2', to: 'n3', type: 'a' },
      { from: 'n3', to: 'n4', type: 'a' },
      { from: 'n1', to: 'n5', type: 'b' },
      { from: 'n5', to: 'n6', type: 'b' },
      { from: 'n6', to: 'n7', type: 'b' },
    ],
    pool: ['ta_f', 'gangcai', 'xiao', 'le', 'neng', 'tingdong', 'hanyu_kr'],
    answer:
      "A: 她刚才笑了。<br>B: 她能听懂韩语。<br><span class='kor'>A: 그녀가 방금 웃었어요.<br>B: 그녀는 한국어를 알아들을 수 있어요.</span>",
  },

  // --- [나머지 6~30단계 유지] ---
  {
    level: 6,
    title: '왕관자리',
    nodes: [
      { id: 'n1', x: 10, y: 30, expect: 'gege' },
      { id: 'n2', x: 30, y: 60, expect: 'bu' },
      { id: 'n3', x: 50, y: 80, expect: 'kan1' },
      { id: 'n4', x: 70, y: 60, expect: 'dianshi' },
      { id: 'n5', x: 90, y: 30, expect: 'dianying' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
    ],
    pool: ['gege', 'bu', 'kan1', 'dianshi', 'dianying'],
    answer:
      "哥哥不看电视和电影。<br><span class='kor'>형은 TV와 영화를 보지 않는다.</span>",
  },
  {
    level: 7,
    title: '북두칠성',
    nodes: [
      { id: 'n1', x: 10, y: 30, expect: 'laoshi' },
      { id: 'n2', x: 25, y: 40, expect: 'bu' },
      { id: 'n3', x: 40, y: 50, expect: 'xihuan1' },
      { id: 'n4', x: 55, y: 60, expect: 'he_v1' },
      { id: 'n5', x: 75, y: 50, expect: 'pijiu' },
      { id: 'n6', x: 65, y: 85, expect: 'kafei' },
      { id: 'n7', x: 85, y: 80, expect: 'shui' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n4', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n7', to: 'n5' },
    ],
    pool: ['laoshi', 'bu', 'xihuan1', 'he_v1', 'pijiu', 'kafei', 'shui'],
    answer:
      "老师不喜欢喝啤酒、咖啡和水。<br><span class='kor'>선생님은 맥주, 커피, 물 마시는 것을 좋아하지 않는다.</span>",
  },
  {
    level: 8,
    title: '백조자리',
    nodes: [
      { id: 'n1', x: 20, y: 50, expect: 'pengyou' },
      { id: 'n2', x: 50, y: 20, expect: 'baba' },
      { id: 'n3', x: 50, y: 50, expect: 'mai1' },
      { id: 'n4', x: 50, y: 80, expect: 'mama' },
      { id: 'n5', x: 80, y: 50, expect: 'shu' },
    ],
    paths: [
      { from: 'n1', to: 'n3' },
      { from: 'n2', to: 'n3' },
      { from: 'n4', to: 'n3' },
      { from: 'n3', to: 'n5' },
    ],
    pool: ['pengyou', 'baba', 'mai1', 'mama', 'shu'],
    answer:
      "朋友、爸爸和妈妈买书。<br><span class='kor'>친구, 아빠, 엄마는 책을 산다.</span>",
  },
  {
    level: 9,
    title: '거문고자리',
    nodes: [
      { id: 'n1', x: 20, y: 20, expect: 'ta' },
      { id: 'n2', x: 40, y: 50, expect: 'ai' },
      { id: 'n3', x: 60, y: 30, expect: 'kan1' },
      { id: 'n4', x: 60, y: 70, expect: 'ting' },
      { id: 'n5', x: 80, y: 50, expect: 'ge' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n2', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n4', to: 'n5' },
    ],
    pool: ['ta', 'ai', 'kan1', 'ting', 'ge'],
    answer:
      "他爱看电影和听歌。<br><span class='kor'>그는 영화를 보고 노래 듣는 것을 사랑한다.</span>",
  },
  {
    level: 10,
    title: '오리온자리',
    nodes: [
      { id: 'n1', x: 20, y: 20, expect: 'wo' },
      { id: 'n2', x: 20, y: 80, expect: 'ta' },
      { id: 'n3', x: 45, y: 50, expect: 'xihuan1' },
      { id: 'n4', x: 65, y: 50, expect: 'chi1' },
      { id: 'n5', x: 85, y: 20, expect: 'mianbao' },
      { id: 'n6', x: 85, y: 80, expect: 'pingguo' },
    ],
    paths: [
      { from: 'n1', to: 'n3' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n4', to: 'n6' },
    ],
    pool: ['wo', 'ta', 'xihuan1', 'chi1', 'mianbao', 'pingguo'],
    answer:
      "我和他喜欢吃面包和苹果。<br><span class='kor'>나와 그는 빵과 사과 먹는 것을 좋아한다.</span>",
  },
  {
    level: 11,
    title: '세페우스자리',
    nodes: [
      { id: 'n1', x: 20, y: 50, expect: 'yeye' },
      { id: 'n2', x: 50, y: 20, expect: 'qu1' },
      { id: 'n3', x: 50, y: 80, expect: 'xihuan1' },
      { id: 'n4', x: 80, y: 35, expect: 'jia' },
      { id: 'n5', x: 80, y: 65, expect: 'cha' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n1', to: 'n3' },
      { from: 'n2', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n4', to: 'n5' },
    ],
    pool: ['yeye', 'qu1', 'xihuan1', 'jia', 'cha'],
    answer:
      "爷爷去家，喜欢茶。<br><span class='kor'>할아버지는 집에 가고, 차를 좋아하신다.</span>",
  },
  {
    level: 12,
    title: '큰개자리',
    nodes: [
      { id: 'n1', x: 15, y: 30, expect: 'wo' },
      { id: 'n2', x: 35, y: 50, expect: 'bu' },
      { id: 'n3', x: 55, y: 30, expect: 'xihuan1' },
      { id: 'n4', x: 55, y: 70, expect: 'chi1' },
      { id: 'n5', x: 75, y: 50, expect: 'fan' },
      { id: 'n6', x: 90, y: 30, expect: 'mian' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n2', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n4', to: 'n5' },
      { from: 'n5', to: 'n6' },
    ],
    pool: ['wo', 'bu', 'xihuan1', 'chi1', 'fan', 'mian'],
    answer:
      "我不喜欢吃饭和面。<br><span class='kor'>나는 밥과 면 먹는 것을 좋아하지 않는다.</span>",
  },
  {
    level: 13,
    title: '목동자리',
    nodes: [
      { id: 'n1', x: 20, y: 50, expect: 'didi' },
      { id: 'n2', x: 40, y: 30, expect: 'mai1' },
      { id: 'n3', x: 40, y: 70, expect: 'kan1' },
      { id: 'n4', x: 60, y: 50, expect: 'shu' },
      { id: 'n5', x: 80, y: 50, expect: 'dianshi' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n1', to: 'n3' },
      { from: 'n2', to: 'n4' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
    ],
    pool: ['didi', 'mai1', 'kan1', 'shu', 'dianshi'],
    answer:
      "弟弟买书，看电视。<br><span class='kor'>남동생은 책을 사고, TV를 본다.</span>",
  },
  {
    level: 14,
    title: '마차부자리',
    nodes: [
      { id: 'n1', x: 15, y: 50, expect: 'meimei' },
      { id: 'n2', x: 40, y: 20, expect: 'xihuan1' },
      { id: 'n3', x: 40, y: 80, expect: 'bu' },
      { id: 'n4', x: 70, y: 30, expect: 'shuo' },
      { id: 'n5', x: 70, y: 70, expect: 'hanyu_zh' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n1', to: 'n3' },
      { from: 'n2', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n4', to: 'n5' },
    ],
    pool: ['meimei', 'xihuan1', 'bu', 'shuo', 'hanyu_zh'],
    answer:
      "妹妹喜欢不说话。<br><span class='kor'>여동생은 중국어로 말하는 것을 좋아하지 않는다.</span>",
  },
  {
    level: 15,
    title: '페가수스자리',
    nodes: [
      { id: 'n1', x: 20, y: 30, expect: 'wo' },
      { id: 'n2', x: 20, y: 70, expect: 'ta' },
      { id: 'n3', x: 50, y: 30, expect: 'ai' },
      { id: 'n4', x: 50, y: 70, expect: 'kan1' },
      { id: 'n5', x: 80, y: 50, expect: 'dianying' },
    ],
    paths: [
      { from: 'n1', to: 'n3' },
      { from: 'n2', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n4', to: 'n5' },
      { from: 'n1', to: 'n4' },
    ],
    pool: ['wo', 'ta', 'ai', 'kan1', 'dianying'],
    answer:
      "我和他都爱看电影。<br><span class='kor'>나와 그는 모두 영화를 보는 것을 사랑한다.</span>",
  },
  {
    level: 16,
    title: '페르세우스자리',
    nodes: [
      { id: 'n1', x: 20, y: 50, expect: 'mama' },
      { id: 'n2', x: 40, y: 50, expect: 'qu1' },
      { id: 'n3', x: 60, y: 20, expect: 'shangdian' },
      { id: 'n4', x: 80, y: 40, expect: 'mai1' },
      { id: 'n5', x: 60, y: 80, expect: 'yiyuan' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n2', to: 'n5' },
    ],
    pool: ['mama', 'qu1', 'shangdian', 'mai1', 'yiyuan'],
    answer:
      "妈妈去商店买东西，去医院。<br><span class='kor'>엄마는 상점에 가서 물건을 사고, 병원에 간다.</span>",
  },
  {
    level: 17,
    title: '안드로메다자리',
    nodes: [
      { id: 'n1', x: 15, y: 50, expect: 'baba' },
      { id: 'n2', x: 35, y: 50, expect: 'xihuan1' },
      { id: 'n3', x: 60, y: 30, expect: 'he_v1' },
      { id: 'n4', x: 85, y: 15, expect: 'pijiu' },
      { id: 'n5', x: 60, y: 70, expect: 'chi1' },
      { id: 'n6', x: 85, y: 85, expect: 'fan' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n2', to: 'n5' },
      { from: 'n5', to: 'n6' },
    ],
    pool: ['baba', 'xihuan1', 'he_v1', 'pijiu', 'chi1', 'fan'],
    answer:
      "爸爸喜欢喝啤酒和吃饭。<br><span class='kor'>아빠는 맥주 마시는 것과 밥 먹는 것을 좋아하신다.</span>",
  },
  {
    level: 18,
    title: '돌고래자리',
    nodes: [
      { id: 'n1', x: 15, y: 70, expect: 'gege' },
      { id: 'n2', x: 35, y: 40, expect: 'bu' },
      { id: 'n3', x: 55, y: 20, expect: 'qu1' },
      { id: 'n4', x: 75, y: 40, expect: 'xuexiao' },
      { id: 'n5', x: 55, y: 60, expect: 'beijing' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n2', to: 'n5' },
    ],
    pool: ['gege', 'bu', 'qu1', 'xuexiao', 'beijing'],
    answer:
      "哥哥不去学校和北京。<br><span class='kor'>형은 학교와 베이징에 가지 않는다.</span>",
  },

  {
    level: 19,
    title: '양자리 (Aries)',
    nodes: [
      { id: 'n1', x: 20, y: 60, expect: 'wo' },
      { id: 'n2', x: 50, y: 40, expect: 'jintian' },
      { id: 'n3', x: 70, y: 45, expect: 'hen' },
      { id: 'n4', x: 90, y: 60, expect: 'gaoxing' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
    ],
    pool: ['wo', 'jintian', 'hen', 'gaoxing'],
    answer: "我今天很高兴。<br><span class='kor'>나는 오늘 매우 기쁘다.</span>",
  },
  {
    level: 20,
    title: '황소자리 (Taurus)',
    nodes: [
      { id: 'n1', x: 15, y: 35, expect: 'baba' },
      { id: 'n2', x: 10, y: 50, expect: 'he_conj1' },
      { id: 'n3', x: 15, y: 65, expect: 'mama' },
      { id: 'n4', x: 25, y: 55, expect: 'jintian' },
      { id: 'n5', x: 25, y: 45, expect: 'dou' },
      { id: 'n6', x: 40, y: 20, expect: 'qu1' },
      { id: 'n7', x: 60, y: 15, expect: 'shangdian' },
      { id: 'n8', x: 80, y: 20, expect: 'mai1' },
      { id: 'n9', x: 40, y: 80, expect: 'xihuan1' },
      { id: 'n10', x: 60, y: 85, expect: 'he_v1' },
      { id: 'n11', x: 80, y: 80, expect: 'kafei' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n3', to: 'n2' },
      { from: 'n2', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n1', to: 'n5' },
      { from: 'n5', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n7', to: 'n8' },
      { from: 'n4', to: 'n9' },
      { from: 'n9', to: 'n10' },
      { from: 'n10', to: 'n11' },
    ],
    pool: [
      'baba',
      'he_conj1',
      'mama',
      'jintian',
      'dou',
      'qu1',
      'shangdian',
      'mai1',
      'xihuan1',
      'he_v1',
      'kafei',
    ],
    answer:
      "爸爸和妈妈今天都去商店买东西，喜欢喝咖啡。<br><span class='kor'>아빠와 엄마는 오늘 모두 상점에 사고, 커피 마시기를 좋아하신다.</span>",
  },
  {
    level: 21,
    title: '쌍둥이자리 (Gemini)',
    nodes: [
      { id: 'n1', x: 25, y: 15, expect: 'yinwei' },
      { id: 'n2', x: 25, y: 30, expect: 'wo' },
      { id: 'n3', x: 25, y: 50, expect: 'de1' },
      { id: 'n4', x: 15, y: 70, expect: 'gege' },
      { id: 'n5', x: 10, y: 85, expect: 'he_conj1' },
      { id: 'n6', x: 35, y: 70, expect: 'jiejie' },
      { id: 'n7', x: 40, y: 85, expect: 'jintian' },
      { id: 'n8', x: 10, y: 45, expect: 'hen' },
      { id: 'n9', x: 40, y: 45, expect: 'mang' },
      { id: 'n10', x: 75, y: 15, expect: 'suoyi' },
      { id: 'n11', x: 75, y: 30, expect: 'ta' },
      { id: 'n12', x: 75, y: 50, expect: 'men' },
      { id: 'n13', x: 65, y: 70, expect: 'bu' },
      { id: 'n14', x: 60, y: 85, expect: 'qu1' },
      { id: 'n15', x: 85, y: 70, expect: 'xuexiao' },
      { id: 'n16', x: 90, y: 85, expect: 'xuexi' },
      { id: 'n17', x: 60, y: 45, expect: 'hanyu_zh' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n3', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n2', to: 'n8' },
      { from: 'n2', to: 'n9' },
      { from: 'n10', to: 'n11' },
      { from: 'n11', to: 'n12' },
      { from: 'n12', to: 'n13' },
      { from: 'n13', to: 'n14' },
      { from: 'n12', to: 'n15' },
      { from: 'n15', to: 'n16' },
      { from: 'n11', to: 'n17' },
      { from: 'n9', to: 'n17' },
    ],
    pool: [
      'yinwei',
      'wo',
      'de1',
      'gege',
      'he_conj1',
      'jiejie',
      'jintian',
      'hen',
      'mang',
      'suoyi',
      'ta',
      'men',
      'bu',
      'qu1',
      'xuexiao',
      'xuexi',
      'hanyu_zh',
    ],
    answer:
      "因为我的哥哥和姐姐今天很忙，所以他们不去学校学习汉语。<br><span class='kor'>나의 형과 누나가 오늘 바빠서, 그들은 학교에 중국어를 배우러 가지 않는다.</span>",
  },
  {
    level: 22,
    title: '게자리 (Cancer)',
    nodes: [
      { id: 'n1', x: 50, y: 50, expect: 'wo' },
      { id: 'n2', x: 50, y: 20, expect: 'jintian' },
      { id: 'n3', x: 30, y: 80, expect: 'bu' },
      { id: 'n4', x: 70, y: 80, expect: 'kan1' },
      { id: 'n5', x: 90, y: 60, expect: 'dianying' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n1', to: 'n3' },
      { from: 'n1', to: 'n4' },
      { from: 'n4', to: 'n5' },
    ],
    pool: ['wo', 'jintian', 'bu', 'kan1', 'dianying'],
    answer:
      "我今天不看电影。<br><span class='kor'>나는 오늘 영화를 안 본다.</span>",
  },
  {
    level: 23,
    title: '사자자리 (Leo)',
    nodes: [
      { id: 'n1', x: 10, y: 60, expect: 'ta' },
      { id: 'n2', x: 15, y: 35, expect: 'jintian' },
      { id: 'n3', x: 30, y: 20, expect: 'zai' },
      { id: 'n4', x: 45, y: 30, expect: 'jia' },
      { id: 'n5', x: 40, y: 55, expect: 'hen' },
      { id: 'n6', x: 25, y: 70, expect: 'gaoxing' },
      { id: 'n7', x: 70, y: 45, expect: 'de1' },
      { id: 'n8', x: 85, y: 70, expect: 'kan1' },
      { id: 'n9', x: 55, y: 85, expect: 'dianshi' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n5', to: 'n6' },
      { from: 'n5', to: 'n7' },
      { from: 'n7', to: 'n8' },
      { from: 'n8', to: 'n9' },
      { from: 'n9', to: 'n6' },
    ],
    pool: [
      'ta',
      'jintian',
      'zai',
      'jia',
      'hen',
      'gaoxing',
      'de1',
      'kan1',
      'dianshi',
    ],
    answer:
      "他今天在家很高兴地看电视。<br><span class='kor'>그는 오늘 집에서 매우 기쁘게 TV를 본다.</span>",
  },
  {
    level: 24,
    title: '처녀자리 (Virgo)',
    nodes: [
      { id: 'n1', x: 15, y: 20, expect: 'wo' },
      { id: 'n2', x: 30, y: 35, expect: 'he_conj1' },
      { id: 'n3', x: 50, y: 30, expect: 'pengyou' },
      { id: 'n4', x: 60, y: 50, expect: 'jintian' },
      { id: 'n5', x: 40, y: 60, expect: 'dou' },
      { id: 'n6', x: 75, y: 45, expect: 'hen' },
      { id: 'n7', x: 88, y: 30, expect: 'xihuan1' },
      { id: 'n8', x: 35, y: 80, expect: 'qu1' },
      { id: 'n9', x: 45, y: 90, expect: 'zhongguo' },
      { id: 'n10', x: 55, y: 80, expect: 'chi1' },
      { id: 'n11', x: 85, y: 60, expect: 'hao' },
      { id: 'n12', x: 75, y: 80, expect: 'de1' },
      { id: 'n13', x: 90, y: 90, expect: 'mian' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n5', to: 'n2' },
      { from: 'n4', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n5', to: 'n8' },
      { from: 'n8', to: 'n9' },
      { from: 'n5', to: 'n10' },
      { from: 'n4', to: 'n11' },
      { from: 'n11', to: 'n12' },
      { from: 'n12', to: 'n13' },
    ],
    pool: [
      'wo',
      'he_conj1',
      'pengyou',
      'jintian',
      'dou',
      'hen',
      'xihuan1',
      'qu1',
      'zhongguo',
      'chi1',
      'hao',
      'de1',
      'mian',
    ],
    answer:
      "我和朋友今天都很喜欢去中国吃好的面。<br><span class='kor'>나와 친구는 오늘 모두 중국에 가서 맛있는 면을 먹는 것을 아주 좋아한다.</span>",
  },
  {
    level: 25,
    title: '천칭자리 (Libra)',
    nodes: [
      { id: 'n1', x: 30, y: 70, expect: 'wo' },
      { id: 'n2', x: 50, y: 40, expect: 'mingtian' },
      { id: 'n3', x: 70, y: 50, expect: 'qu1' },
      { id: 'n4', x: 60, y: 80, expect: 'shangdian' },
      { id: 'n5', x: 45, y: 15, expect: 'mai1' },
      { id: 'n6', x: 90, y: 35, expect: 'shui' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n1' },
      { from: 'n2', to: 'n5' },
      { from: 'n3', to: 'n6' },
    ],
    pool: ['wo', 'mingtian', 'qu1', 'shangdian', 'mai1', 'shui'],
    answer:
      "我明天去商店买水。<br><span class='kor'>나는 내일 상점에 물을 사러 간다.</span>",
  },
  {
    level: 26,
    title: '전갈자리 (Scorpio)',
    nodes: [
      { id: 'n1', x: 10, y: 20, expect: 'wo' },
      { id: 'n2', x: 15, y: 40, expect: 'de1' },
      { id: 'n3', x: 10, y: 60, expect: 'yeye' },
      { id: 'n4', x: 30, y: 40, expect: 'he_conj1' },
      { id: 'n5', x: 45, y: 50, expect: 'nainai' },
      { id: 'n6', x: 55, y: 60, expect: 'dou' },
      { id: 'n7', x: 60, y: 75, expect: 'bu' },
      { id: 'n8', x: 65, y: 90, expect: 'xihuan1' },
      { id: 'n9', x: 75, y: 90, expect: 'qu1' },
      { id: 'n10', x: 85, y: 85, expect: 'shangdian' },
      { id: 'n11', x: 88, y: 70, expect: 'mai1' },
      { id: 'n12', x: 85, y: 55, expect: 'pingguo' },
      { id: 'n13', x: 75, y: 50, expect: 'he_conj2' },
      { id: 'n14', x: 80, y: 35, expect: 'mianbao' },
      { id: 'n15', x: 92, y: 35, expect: 'le' },
    ],
    paths: [
      { from: 'n1', to: 'n4' },
      { from: 'n2', to: 'n4' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n5', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n7', to: 'n8' },
      { from: 'n8', to: 'n9' },
      { from: 'n9', to: 'n10' },
      { from: 'n10', to: 'n11' },
      { from: 'n11', to: 'n12' },
      { from: 'n12', to: 'n13' },
      { from: 'n13', to: 'n14' },
      { from: 'n14', to: 'n15' },
    ],
    pool: [
      'wo',
      'de1',
      'yeye',
      'he_conj1',
      'nainai',
      'dou',
      'bu',
      'xihuan1',
      'qu1',
      'shangdian',
      'mai1',
      'pingguo',
      'he_conj2',
      'mianbao',
      'le',
    ],
    answer:
      "我的爷爷和奶奶都不喜欢去商店买苹果和面包了。<br><span class='kor'>나의 조부모님은 모두 상점에 가서 사과와 빵을 사는 것을 좋아하시지 않게 되었다.</span>",
  },
  {
    level: 27,
    title: '사수자리 (Sagittarius)',
    nodes: [
      { id: 'n1', x: 10, y: 40, expect: 'laoshi' },
      { id: 'n2', x: 15, y: 20, expect: 'jintian' },
      { id: 'n3', x: 35, y: 25, expect: 'qu1' },
      { id: 'n4', x: 35, y: 50, expect: 'beijing' },
      { id: 'n5', x: 50, y: 15, expect: 'suoyi' },
      { id: 'n6', x: 65, y: 25, expect: 'wo' },
      { id: 'n7', x: 55, y: 50, expect: 'men' },
      { id: 'n8', x: 65, y: 80, expect: 'zai' },
      { id: 'n9', x: 25, y: 80, expect: 'jia' },
      { id: 'n10', x: 80, y: 40, expect: 'kan1' },
      { id: 'n11', x: 92, y: 30, expect: 'dianshi' },
      { id: 'n12', x: 85, y: 75, expect: 'ting' },
      { id: 'n13', x: 95, y: 85, expect: 'ge' },
      { id: 'n14', x: 85, y: 60, expect: 'le' },
      { id: 'n15', x: 90, y: 65, expect: 'ba' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n1' },
      { from: 'n4', to: 'n7' },
      { from: 'n7', to: 'n8' },
      { from: 'n8', to: 'n9' },
      { from: 'n9', to: 'n1' },
      { from: 'n3', to: 'n5' },
      { from: 'n5', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n7', to: 'n10' },
      { from: 'n10', to: 'n11' },
      { from: 'n8', to: 'n12' },
      { from: 'n12', to: 'n13' },
      { from: 'n8', to: 'n14' },
      { from: 'n14', to: 'n15' },
    ],
    pool: [
      'laoshi',
      'jintian',
      'qu1',
      'beijing',
      'suoyi',
      'wo',
      'men',
      'zai',
      'jia',
      'kan1',
      'dianshi',
      'ting',
      'ge',
      'le',
      'ba',
    ],
    answer:
      "老师今天去北京，所以我们在家看电视、听歌了吧。<br><span class='kor'>선생님이 오늘 베이징에 가셔서, 우리는 집에서 TV를 보고 노래를 들었을 것이다.</span>",
  },
  {
    level: 28,
    title: '염소자리 (Capricorn)',
    nodes: [
      { id: 'n1', x: 15, y: 20, expect: 'baba' },
      { id: 'n2', x: 30, y: 35, expect: 'he_conj1' },
      { id: 'n3', x: 50, y: 55, expect: 'mama' },
      { id: 'n4', x: 60, y: 75, expect: 'mingtian' },
      { id: 'n5', x: 75, y: 85, expect: 'qu1' },
      { id: 'n6', x: 90, y: 65, expect: 'yiyuan' },
      { id: 'n7', x: 80, y: 45, expect: 'kan1' },
      { id: 'n8', x: 60, y: 35, expect: 'yisheng' },
      { id: 'n9', x: 45, y: 25, expect: 'wo' },
      { id: 'n10', x: 25, y: 15, expect: 'bu' },
      { id: 'n11', x: 10, y: 30, expect: 'qu2' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n5', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n7', to: 'n8' },
      { from: 'n8', to: 'n9' },
      { from: 'n9', to: 'n10' },
      { from: 'n10', to: 'n11' },
      { from: 'n11', to: 'n1' },
    ],
    pool: [
      'baba',
      'he_conj1',
      'mama',
      'mingtian',
      'qu1',
      'yiyuan',
      'kan1',
      'yisheng',
      'wo',
      'bu',
      'qu2',
    ],
    answer:
      "爸爸和妈妈明天去医院看医生，我不去。<br><span class='kor'>아빠와 엄마는 내일 병원에 의사를 보러 가고, 나는 가지 않는다.</span>",
  },
  {
    level: 29,
    title: '물병자리 (Aquarius)',
    nodes: [
      { id: 'n1', x: 20, y: 20, expect: 'didi' },
      { id: 'n2', x: 35, y: 15, expect: 'he_conj1' },
      { id: 'n3', x: 45, y: 30, expect: 'meimei' },
      { id: 'n4', x: 30, y: 40, expect: 'he_conj2' },
      { id: 'n5', x: 60, y: 40, expect: 'wo' },
      { id: 'n6', x: 75, y: 30, expect: 'dou' },
      { id: 'n7', x: 90, y: 45, expect: 'hen' },
      { id: 'n8', x: 40, y: 60, expect: 'xihuan1' },
      { id: 'n9', x: 55, y: 55, expect: 'he_v1' },
      { id: 'n10', x: 75, y: 75, expect: 'shui' },
      { id: 'n11', x: 90, y: 65, expect: 'ye' },
      { id: 'n12', x: 90, y: 85, expect: 'xihuan2' },
      { id: 'n13', x: 80, y: 88, expect: 'cha' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n1' },
      { from: 'n3', to: 'n5' },
      { from: 'n5', to: 'n6' },
      { from: 'n6', to: 'n7' },
      { from: 'n4', to: 'n8' },
      { from: 'n8', to: 'n9' },
      { from: 'n9', to: 'n10' },
      { from: 'n10', to: 'n11' },
      { from: 'n11', to: 'n12' },
      { from: 'n12', to: 'n13' },
    ],
    pool: [
      'didi',
      'he_conj1',
      'meimei',
      'he_conj2',
      'wo',
      'dou',
      'hen',
      'xihuan1',
      'he_v1',
      'shui',
      'ye',
      'xihuan2',
      'cha',
    ],
    answer:
      "弟弟、妹妹和我都喜欢喝水，也喜欢喝茶。<br><span class='kor'>남동생, 여동생과 나는 모두 물 마시는 것을 매우 좋아하고, 차 마시는 것도 좋아한다.</span>",
  },
  {
    level: 30,
    title: '물고기자리 (Pisces)',
    nodes: [
      { id: 'n1', x: 10, y: 30, expect: 'wo' },
      { id: 'n2', x: 15, y: 15, expect: 'de1' },
      { id: 'n3', x: 25, y: 20, expect: 'baba' },
      { id: 'n4', x: 35, y: 35, expect: 'he_conj1' },
      { id: 'n5', x: 25, y: 50, expect: 'mama' },
      { id: 'n6', x: 15, y: 45, expect: 'dou' },
      { id: 'n7', x: 45, y: 50, expect: 'hen' },
      { id: 'n8', x: 55, y: 65, expect: 'xihuan1' },
      { id: 'n9', x: 65, y: 80, expect: 'chi1' },
      { id: 'n10', x: 75, y: 60, expect: 'pingguo' },
      { id: 'n11', x: 85, y: 45, expect: 'he_conj2' },
      { id: 'n12', x: 88, y: 35, expect: 'mianbao' },
      { id: 'n13', x: 78, y: 20, expect: 'yinwei' },
      { id: 'n14', x: 85, y: 10, expect: 'ye' },
      { id: 'n15', x: 95, y: 15, expect: 'hao' },
      { id: 'n16', x: 95, y: 28, expect: 'chi2' },
      { id: 'n17', x: 88, y: 45, expect: 'le' },
    ],
    paths: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n4', to: 'n5' },
      { from: 'n5', to: 'n6' },
      { from: 'n6', to: 'n1' },
      { from: 'n4', to: 'n7' },
      { from: 'n7', to: 'n8' },
      { from: 'n8', to: 'n9' },
      { from: 'n9', to: 'n10' },
      { from: 'n10', to: 'n11' },
      { from: 'n11', to: 'n12' },
      { from: 'n12', to: 'n13' },
      { from: 'n13', to: 'n14' },
      { from: 'n14', to: 'n15' },
      { from: 'n15', to: 'n16' },
      { from: 'n16', to: 'n17' },
      { from: 'n17', to: 'n12' },
    ],
    pool: [
      'wo',
      'de1',
      'baba',
      'he_conj1',
      'mama',
      'dou',
      'hen',
      'xihuan1',
      'chi1',
      'pingguo',
      'he_conj2',
      'mianbao',
      'yinwei',
      'ye',
      'hao',
      'chi2',
      'le',
    ],
    answer:
      "我的爸爸和妈妈都很喜欢吃苹果和面包，因为也很好吃了。<br><span class='kor'>나의 아빠와 엄마는 모두 사과와 빵을 먹는 것을 좋아하신다. 왜냐하면 역시 맛있어졌기 때문이다.</span>",
  },
];

const TOTAL_STAGES = STAGES.length;
